# Ensure Apache is installed
package { 'apache2':
  ensure => installed,
}

# Ensure Apache is running
service { 'apache2':
  ensure => running,
  enable => true,
}

# Use strace to find the issue with Apache and fix it
exec { 'fix-apache':
  command     => 'strace -o /tmp/strace.out -p $(pgrep apache2) & sleep 1 && curl 127.0.0.1',
  path        => ['/usr/bin', '/bin'],
  refreshonly => true,
  subscribe   => Service['apache2'],
  notify      => Service['apache2'],
}

# Fix the issue with Apache by updating the Apache configuration file
file { '/etc/apache2/sites-enabled/000-default.conf':
  ensure  => present,
  content => "# This file was automatically generated by Puppet\n\n<VirtualHost *:80>\n\tServerAdmin webmaster@localhost\n\tDocumentRoot /var/www/html\n\tErrorLog \${APACHE_LOG_DIR}/error.log\n\tCustomLog \${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>\n",
  require => Exec['fix-apache'],
}

# Reload Apache after updating the configuration file
exec { 'reload-apache':
  command   => '/usr/sbin/service apache2 reload',
  path      => ['/usr/bin', '/bin'],
  subscribe => File['/etc/apache2/sites-enabled/000-default.conf'],
  notify    => Service['apache2'],
}

